version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: moaishelper
    networks:
      - app_network
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    networks:
      - app_network
    depends_on:
      - postgresdb
    restart: always
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/moaishelper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"
    volumes:
      - app_resources:/app_working_dir/src/main/resources

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
  app_resources: