spring.application.name=tgbot
bot.name=Moais Helper
bot.token=7872248669:AAEUgn9ysh9BwOF9k-cB9IPVNqUpKPdUCgI

# db related setting
spring.datasource.url=jdbc:postgresql://localhost:5432/moaishelper
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true