spring.application.name=tgbot
bot.name=Moais Helper
bot.token=7201467559:AAFUW_ZCUX-HcdLQ1WyTB3LO7TETZcse-Og

#db related setting
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/moaishelper
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true