SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.status
    DROP CONSTRAINT status_pkey;
DROP TABLE IF EXISTS public.status;

--
-- TOC entry 220 (class 1259 OID 100123)
-- Name: status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.status (
                               id integer NOT NULL,
                               description character varying(255) NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 100122)
-- Name: status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

--
-- TOC entry 3418 (class 0 OID 100123)
-- Dependencies: 220
-- Data for Name: status; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.status (id, description) VALUES (1, 'No input');
INSERT INTO public.status (id, description) VALUES (2, 'Group title input');
INSERT INTO public.status (id, description) VALUES (3, 'User invite input');
INSERT INTO public.status (id, description) VALUES (4, 'Group message input');
INSERT INTO public.status (id, description) VALUES (5, 'Schedule two columns file input');
INSERT INTO public.status (id, description) VALUES (6, 'All message input');
INSERT INTO public.status (id, description) VALUES (7, 'Lesson title input');
INSERT INTO public.status (id, description) VALUES (8, 'Teacher name input');
INSERT INTO public.status (id, description) VALUES (9, 'Auditorium title input');
INSERT INTO public.status (id, description) VALUES (10, 'Lesson time input');
INSERT INTO public.status (id, description) VALUES (11, 'Schedule two columns file input');
INSERT INTO public.status (id, description) VALUES (12, 'Homework file input');



--
-- TOC entry 3428 (class 0 OID 0)
-- Dependencies: 219
-- Name: status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.status_id_seq', 1, false);


--
-- TOC entry 3253 (class 2606 OID 100127)
-- Name: status status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_pkey PRIMARY KEY (id);