/*--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Ubuntu 16.8-1.pgdg22.04+1)
-- Dumped by pg_dump version 17.4 (Ubuntu 17.4-1.pgdg22.04+2)

-- Started on 2025-05-06 21:22:00 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT fksq4vihylk98o5avffnp3rd5bn;
ALTER TABLE IF EXISTS ONLY public.group_user DROP CONSTRAINT fkrqeo92wyuy7jcc54mfbln3wme;
ALTER TABLE IF EXISTS ONLY public.groupe DROP CONSTRAINT fkhfqh1jxcqos0xsn55k9kb86aw;
ALTER TABLE IF EXISTS ONLY public.group_file DROP CONSTRAINT fkgkefqugyes4pqq8rckqp0f9xh;
ALTER TABLE IF EXISTS ONLY public.user_settings DROP CONSTRAINT fk8v82nj88rmai0nyck19f873dw;
ALTER TABLE IF EXISTS ONLY public.group_file DROP CONSTRAINT fk4x8t47t2vfo4fi2ux2sulcia8;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT fk3m08uc0bd36m6tgp3g65m20dl;
ALTER TABLE IF EXISTS ONLY public.group_user DROP CONSTRAINT fk2wx7g2d3qismbh8hxo7f7m369;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT users_pkey;
ALTER TABLE IF EXISTS ONLY public.user_settings DROP CONSTRAINT user_settings_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT uknr2rmfhq6wfp39vcduy7iketb;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx;
ALTER TABLE IF EXISTS ONLY public.groupe DROP CONSTRAINT ukjx32y1rwnquvvifj8sostpn42;
ALTER TABLE IF EXISTS ONLY public.groupe DROP CONSTRAINT groupe_pkey;
ALTER TABLE IF EXISTS ONLY public.group_user DROP CONSTRAINT group_user_pkey;
ALTER TABLE IF EXISTS ONLY public.group_file DROP CONSTRAINT group_file_pkey;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.user_settings;
DROP TABLE IF EXISTS public.groupe;
DROP TABLE IF EXISTS public.group_user;
DROP TABLE IF EXISTS public.group_file;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 100110)
-- Name: group_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_file (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    days_to_store integer,
    file_name character varying(255),
    group_id bigint,
    sender_id bigint
);


--
-- TOC entry 218 (class 1259 OID 100115)
-- Name: group_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_user (
    admin boolean NOT NULL,
    settings bytea,
    user_id bigint NOT NULL,
    group_id bigint NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 100105)
-- Name: groupe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groupe (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL,
    owner_id bigint NOT NULL
);


--
-- TOC entry 215 (class 1259 OID 100104)
-- Name: groupe_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.groupe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groupe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 100136)
-- Name: user_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_settings (
    notification_hours smallint NOT NULL,
    notification_minutes smallint NOT NULL,
    notifications_enabled boolean NOT NULL,
    time_zone_id character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 100129)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    chat_id bigint NOT NULL,
    first_name character varying(255) NOT NULL,
    registered_at timestamp(6) without time zone NOT NULL,
    user_name character varying(255) NOT NULL,
    selected_group_id bigint,
    status_id integer NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 100128)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3415 (class 0 OID 100110)
-- Dependencies: 217
-- Data for Name: group_file; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 3416 (class 0 OID 100115)
-- Dependencies: 218
-- Data for Name: group_user; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787000', 2, 2);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 8, 2);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 15, 2);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b7870707372000f6a6176612e6c616e672e53686f7274684d37133460da5202000153000576616c7565787200106a6176612e6c616e672e4e756d62657286ac951d0b94e08b02000078700003737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787000', 1, 3);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 3, 3);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 4, 3);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 12, 3);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 14, 3);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707372000f6a6176612e6c616e672e53686f7274684d37133460da5202000153000576616c7565787200106a6176612e6c616e672e4e756d62657286ac951d0b94e08b020000787000057371007e00040002737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 1, 5);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 6, 5);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 9, 5);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 10, 5);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 11, 5);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 13, 5);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 9, 6);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (false, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 9, 7);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 13, 7);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 7, 8);
INSERT INTO public.group_user (admin, settings, user_id, group_id) VALUES (true, '\xaced000573720030696f2e7467626f742e6d6f61697368656c7065722e6d6f64656c2e41646d696e5363686564756c6553657474696e6773f3f41261735c1b390200034c00096c6573736f6e4e756d7400114c6a6176612f6c616e672f53686f72743b4c00077765656b44617971007e00014c00077765656b4e756d7400134c6a6176612f6c616e672f426f6f6c65616e3b78707070737200116a6176612e6c616e672e426f6f6c65616ecd207280d59cfaee0200015a000576616c7565787001', 24, 10);


--
-- TOC entry 3414 (class 0 OID 100105)
-- Dependencies: 216
-- Data for Name: groupe; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.groupe (id, created_at, name, owner_id) VALUES (2, '2025-02-02 11:59:49.928', 'БТСиТ-2_1_24-25', 2);
INSERT INTO public.groupe (id, created_at, name, owner_id) VALUES (3, '2025-02-02 12:01:14.346', 'Ин.Яз 24/1', 1);
INSERT INTO public.groupe (id, created_at, name, owner_id) VALUES (5, '2025-02-02 19:12:00.507', '25/2', 6);
INSERT INTO public.groupe (id, created_at, name, owner_id) VALUES (6, '2025-02-03 18:04:09.82', 'Поло', 9);
INSERT INTO public.groupe (id, created_at, name, owner_id) VALUES (7, '2025-02-06 08:39:22.425', 'джубга', 13);
INSERT INTO public.groupe (id, created_at, name, owner_id) VALUES (8, '2025-02-09 14:54:50.164', 'Шиян Валерий Игоревич', 7);
INSERT INTO public.groupe (id, created_at, name, owner_id) VALUES (10, '2025-04-07 16:52:00.813', '📞 Контакты', 24);


--
-- TOC entry 3421 (class 0 OID 100136)
-- Dependencies: 223
-- Data for Name: user_settings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (7, 30, true, 'Europe/Moscow', 1);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 2);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 3);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 4);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 5);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (7, 0, false, 'Europe/Moscow', 6);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 7);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 8);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (6, 0, true, 'Europe/Moscow', 9);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 10);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (22, 15, true, 'Europe/Moscow', 11);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 12);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (7, 0, true, 'Europe/Moscow', 13);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 14);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 15);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 16);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 17);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 18);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 19);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 20);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 21);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 22);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 23);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 24);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 25);
INSERT INTO public.user_settings (notification_hours, notification_minutes, notifications_enabled, time_zone_id, user_id) VALUES (12, 0, true, 'Europe/Moscow', 26);


--
-- TOC entry 3420 (class 0 OID 100129)
-- Dependencies: 222
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (1, 5254745148, 'Юра', '2025-02-02 11:52:11.927', 'YDKrivoshey', 5, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (2, 971641163, 'Максим', '2025-02-02 11:58:23.353', 'MiraiAkihiko', 2, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (3, 631190253, 'Elizaveta', '2025-02-02 13:47:36.499', 'mon_eliza', 3, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (4, 409501911, 'Someone', '2025-02-02 16:31:56.975', 'someoneenoemos', 3, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (5, 1192589017, 'Niki', '2025-02-02 19:02:14.014', 'Niki_fx', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (6, 534648119, 'Nick', '2025-02-02 19:08:22.08', 'mirqet', 5, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (7, 685606015, 'Валерий', '2025-02-02 19:17:21.832', 'ValeriyShiyan', 8, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (8, 1729448174, 'Диана', '2025-02-03 06:34:20.66', 'Jtttyd', 2, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (9, 989138081, 'Markellowww', '2025-02-03 18:04:04.605', 'markellowww', 5, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (10, 1318876290, 'Хуа', '2025-02-04 06:24:53.131', 'x_ashley', 5, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (11, 1228728938, 'Sofa', '2025-02-04 06:29:50.527', 'sona_umanets', 5, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (12, 523028071, 'предательница', '2025-02-04 15:45:01.154', 'qhw_ysh', 3, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (13, 926190032, 'Алина', '2025-02-06 08:35:37.064', 'allgvsk', 5, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (14, 531838285, 'Бодоньи Арина', '2025-02-06 15:36:36.502', 'a_bodony', 3, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (15, 859662190, 'Дина', '2025-02-07 04:37:21.651', 'dionica_di', 2, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (16, 940319410, 'Михаил', '2025-02-12 13:03:41.849', 'michael4krd', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (17, 1320750060, 'Никита', '2025-02-12 13:29:57.565', 'yuomkum', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (18, 1239737301, '­Денис', '2025-02-12 13:31:29.225', 'Maybachh7', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (19, 700186952, 'Сасиська', '2025-02-12 13:45:37.148', 'sasiska992', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (20, 1418177520, 'klvlsk', '2025-02-12 13:52:30.658', 'Susikti', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (21, 5151529390, 'Linkin', '2025-02-23 17:37:13.252', 'vellunnn', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (22, 479601483, 'Макс', '2025-03-20 09:28:04.966', 'mattakvshi', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (23, 745033571, 'Роман', '2025-03-28 15:43:19.654', 'stromale', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (24, 221156472, 'Мария Михайловна', '2025-04-01 09:23:14.431', 'mmaruusya', 10, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (25, 1391480963, 'George', '2025-04-03 13:51:21.967', 'nighteny', NULL, 1);
INSERT INTO public.users (id, chat_id, first_name, registered_at, user_name, selected_group_id, status_id) VALUES (26, 1030941293, 'Momr', '2025-04-09 12:34:24.904', 'momr_77', NULL, 1);


--
-- TOC entry 3427 (class 0 OID 0)
-- Dependencies: 215
-- Name: groupe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.groupe_id_seq', 1, false);


--
-- TOC entry 3429 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 3249 (class 2606 OID 100114)
-- Name: group_file group_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_file
    ADD CONSTRAINT group_file_pkey PRIMARY KEY (id);


--
-- TOC entry 3251 (class 2606 OID 100121)
-- Name: group_user group_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_user
    ADD CONSTRAINT group_user_pkey PRIMARY KEY (group_id, user_id);


--
-- TOC entry 3245 (class 2606 OID 100109)
-- Name: groupe groupe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groupe
    ADD CONSTRAINT groupe_pkey PRIMARY KEY (id);

--
-- TOC entry 3247 (class 2606 OID 100142)
-- Name: groupe ukjx32y1rwnquvvifj8sostpn42; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groupe
    ADD CONSTRAINT ukjx32y1rwnquvvifj8sostpn42 UNIQUE (owner_id);


--
-- TOC entry 3255 (class 2606 OID 100146)
-- Name: users ukk8d0f2n7n88w1a16yhua64onx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx UNIQUE (user_name);


--
-- TOC entry 3257 (class 2606 OID 100144)
-- Name: users uknr2rmfhq6wfp39vcduy7iketb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uknr2rmfhq6wfp39vcduy7iketb UNIQUE (chat_id);


--
-- TOC entry 3261 (class 2606 OID 100140)
-- Name: user_settings user_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_pkey PRIMARY KEY (user_id);


--
-- TOC entry 3259 (class 2606 OID 100135)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3265 (class 2606 OID 100162)
-- Name: group_user fk2wx7g2d3qismbh8hxo7f7m369; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_user
    ADD CONSTRAINT fk2wx7g2d3qismbh8hxo7f7m369 FOREIGN KEY (group_id) REFERENCES public.groupe(id);


--
-- TOC entry 3267 (class 2606 OID 100177)
-- Name: users fk3m08uc0bd36m6tgp3g65m20dl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk3m08uc0bd36m6tgp3g65m20dl FOREIGN KEY (status_id) REFERENCES public.status(id);


--
-- TOC entry 3263 (class 2606 OID 100157)
-- Name: group_file fk4x8t47t2vfo4fi2ux2sulcia8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_file
    ADD CONSTRAINT fk4x8t47t2vfo4fi2ux2sulcia8 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- TOC entry 3269 (class 2606 OID 100182)
-- Name: user_settings fk8v82nj88rmai0nyck19f873dw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT fk8v82nj88rmai0nyck19f873dw FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3264 (class 2606 OID 100152)
-- Name: group_file fkgkefqugyes4pqq8rckqp0f9xh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_file
    ADD CONSTRAINT fkgkefqugyes4pqq8rckqp0f9xh FOREIGN KEY (group_id) REFERENCES public.groupe(id);


--
-- TOC entry 3262 (class 2606 OID 100147)
-- Name: groupe fkhfqh1jxcqos0xsn55k9kb86aw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groupe
    ADD CONSTRAINT fkhfqh1jxcqos0xsn55k9kb86aw FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- TOC entry 3266 (class 2606 OID 100167)
-- Name: group_user fkrqeo92wyuy7jcc54mfbln3wme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_user
    ADD CONSTRAINT fkrqeo92wyuy7jcc54mfbln3wme FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3268 (class 2606 OID 100172)
-- Name: users fksq4vihylk98o5avffnp3rd5bn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fksq4vihylk98o5avffnp3rd5bn FOREIGN KEY (selected_group_id) REFERENCES public.groupe(id);


-- Completed on 2025-05-06 21:22:03 MSK

--
-- PostgreSQL database dump complete
--

